// app/head.tsx
export default function Head() {
    return (
        <>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="manifest" href="/manifest.json" />
            <link rel="icon" href="/icons/icon-192x192.png" />
            <meta name="theme-color" content="#000000" />
            <meta name="mobile-web-app-capable" content="yes" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta name="apple-mobile-web-app-status-bar-style" content="black" />
            <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        </>
    );
}
