# /home/ubuntu/jenkins-data/workspace/mmmr-backend-develop
version: '3.8'

services:
  # backend
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    env_file:
      - /home/ubuntu/jenkins-data/workspace/mmmr-backend-develop/BE/.env
    expose:
      - "8088"
    depends_on:
      - redis

  # redis 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/jenkins_home/workspace/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

