# /var/.../workspace/mmmr-backend-develop
version: '3.8'

services:
  # backend
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    env_file:
      - ./BE/.env
    network_mode: host
    expose:
      - "8088"
