# /home/ubuntu/jenkins-data/workspace/mmmr-backend-develop
version: '3.8'

services:
  # backend
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:mysql://172.17.0.1:3306/mmmr?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&maxAllowedPacket=67108864
      - DB_USERNAME=mmmruser
      - DB_PASSWORD=mysqlformmmr703
    expose:
      - "8088"
    depends_on:
      - redis

  # redis 
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - /var/jenkins_home/workspace/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

