### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(IoT_simulator)
add_subdirectory(IoT_simulatorContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    IoT_simulatorplugin
    IoT_simulatorContentplugin)