# default 프로필
spring:
  config:
    activate:
      on-profile: default
  application:
    name: MMMR
  jackson:
    time-zone: Asia/Seoul

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: embedded

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  file:
    upload:
      path: ${FILE_STORAGE_PATH}
    storage:
      path: ${FILE_STORAGE_PATH}
    csv:
      upload-dir: ${FILE_STORAGE_PATH}/csv

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 1000
          starttls:
            enable: true

  # 캐시 설정
  cache:
    type: redis
    cache-names: weatherCache,forecastCache
    redis:
      time-to-live: ${REDIS_TTL:3600000}

jwt:
  secret: ${JWT_SECRET}
  issuer: mmmr-auth
  subject-prefix: mmmr
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  temporaryTokenExpiration: ${JWT_TEMPORARY_TOKEN_EXPIRATION}

cookie:
  secure-flag: false

server:
  port: ${SERVER_PORT:8088}
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: ""

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE:DEBUG}
    com.ssafy: ${LOG_LEVEL_APP:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    operations-sorter: method

openweather:
  api:
    key: ${OPENWEATHER_API_KEY}
    url: ${OPENWEATHER_API_URL}
    cache:
      ttl: 1800000  # 30분

vworld:
  api:
    key: ${VWORLD_API_KEY}
    geocoder:
      url: ${VWORLD_GEOCODER_URL}

seoul:
  metro:
    api:
      key: ${METRO_API_KEY}
      url: ${METRO_API_URL}
  bus:
    api:
      key: ${BUS_API_KEY}
      url: ${BUS_API_URL}

cache:
  type: redis
  redis:
    time-to-live: ${REDIS_TTL:3600000}

video:
  api:
    key: ${YOUTUBE_API_KEY}
    url: ${YOUTUBE_API_URL}
---
# test 프로필
spring:
  config:
    activate:
      on-profile: test
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: mmmr-scheduler-test-
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    com.ssafy.mmmr: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.test: DEBUG
    org.springframework.transaction: DEBUG